
services:
  git-sync:
    image: ghcr.io/akashrajpurohit/git-sync:v0.20.0
    container_name: git-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${GITSYNC_CONFIG_PATH}:/git-sync/config.yaml
      - ${GITSYNC_BACKUP_PATH}:/backups
    restart: unless-stopped 